package org.iemm.sicomoro.db.dao;

import java.util.Date;

public class Contributor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contributor.idContributor
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    private Integer idContributor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contributor.name
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contributor.lastName
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contributor.secondLastName
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    private String secondLastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contributor.createDate
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contributor.updateDate
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contributor.idContributor
     *
     * @return the value of contributor.idContributor
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public Integer getIdContributor() {
        return idContributor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contributor.idContributor
     *
     * @param idContributor the value for contributor.idContributor
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public void setIdContributor(Integer idContributor) {
        this.idContributor = idContributor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contributor.name
     *
     * @return the value of contributor.name
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contributor.name
     *
     * @param name the value for contributor.name
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contributor.lastName
     *
     * @return the value of contributor.lastName
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contributor.lastName
     *
     * @param lastName the value for contributor.lastName
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contributor.secondLastName
     *
     * @return the value of contributor.secondLastName
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public String getSecondLastName() {
        return secondLastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contributor.secondLastName
     *
     * @param secondLastName the value for contributor.secondLastName
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public void setSecondLastName(String secondLastName) {
        this.secondLastName = secondLastName == null ? null : secondLastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contributor.createDate
     *
     * @return the value of contributor.createDate
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contributor.createDate
     *
     * @param createDate the value for contributor.createDate
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contributor.updateDate
     *
     * @return the value of contributor.updateDate
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contributor.updateDate
     *
     * @param updateDate the value for contributor.updateDate
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}