package org.iemm.sicomoro.db.dao;

import java.math.BigDecimal;
import java.util.Date;

public class Corte {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column corte.idCorte
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    private Integer idCorte;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column corte.fechaCorte
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    private Date fechaCorte;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column corte.saldoAnterior
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    private BigDecimal saldoAnterior;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column corte.saldoActual
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    private BigDecimal saldoActual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column corte.usuarioCreacion
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    private String usuarioCreacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column corte.fechaCreacion
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    private Date fechaCreacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column corte.descripcion
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    private String descripcion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column corte.idCorte
     *
     * @return the value of corte.idCorte
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public Integer getIdCorte() {
        return idCorte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column corte.idCorte
     *
     * @param idCorte the value for corte.idCorte
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public void setIdCorte(Integer idCorte) {
        this.idCorte = idCorte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column corte.fechaCorte
     *
     * @return the value of corte.fechaCorte
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public Date getFechaCorte() {
        return fechaCorte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column corte.fechaCorte
     *
     * @param fechaCorte the value for corte.fechaCorte
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public void setFechaCorte(Date fechaCorte) {
        this.fechaCorte = fechaCorte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column corte.saldoAnterior
     *
     * @return the value of corte.saldoAnterior
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public BigDecimal getSaldoAnterior() {
        return saldoAnterior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column corte.saldoAnterior
     *
     * @param saldoAnterior the value for corte.saldoAnterior
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public void setSaldoAnterior(BigDecimal saldoAnterior) {
        this.saldoAnterior = saldoAnterior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column corte.saldoActual
     *
     * @return the value of corte.saldoActual
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public BigDecimal getSaldoActual() {
        return saldoActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column corte.saldoActual
     *
     * @param saldoActual the value for corte.saldoActual
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public void setSaldoActual(BigDecimal saldoActual) {
        this.saldoActual = saldoActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column corte.usuarioCreacion
     *
     * @return the value of corte.usuarioCreacion
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public String getUsuarioCreacion() {
        return usuarioCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column corte.usuarioCreacion
     *
     * @param usuarioCreacion the value for corte.usuarioCreacion
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion == null ? null : usuarioCreacion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column corte.fechaCreacion
     *
     * @return the value of corte.fechaCreacion
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column corte.fechaCreacion
     *
     * @param fechaCreacion the value for corte.fechaCreacion
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column corte.descripcion
     *
     * @return the value of corte.descripcion
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column corte.descripcion
     *
     * @param descripcion the value for corte.descripcion
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion == null ? null : descripcion.trim();
    }
}