package org.iemm.sicomoro.db.dao;

import java.util.Date;

public class MovementType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movementType.idMovementType
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    private Integer idMovementType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movementType.name
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movementType.idcMovementSign
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    private Integer idcMovementSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movementType.createDate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movementType.updateDate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movementType.idMovementType
     *
     * @return the value of movementType.idMovementType
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public Integer getIdMovementType() {
        return idMovementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movementType.idMovementType
     *
     * @param idMovementType the value for movementType.idMovementType
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public void setIdMovementType(Integer idMovementType) {
        this.idMovementType = idMovementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movementType.name
     *
     * @return the value of movementType.name
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movementType.name
     *
     * @param name the value for movementType.name
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movementType.idcMovementSign
     *
     * @return the value of movementType.idcMovementSign
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public Integer getIdcMovementSign() {
        return idcMovementSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movementType.idcMovementSign
     *
     * @param idcMovementSign the value for movementType.idcMovementSign
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public void setIdcMovementSign(Integer idcMovementSign) {
        this.idcMovementSign = idcMovementSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movementType.createDate
     *
     * @return the value of movementType.createDate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movementType.createDate
     *
     * @param createDate the value for movementType.createDate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movementType.updateDate
     *
     * @return the value of movementType.updateDate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movementType.updateDate
     *
     * @param updateDate the value for movementType.updateDate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}