package org.iemm.sicomoro.db.dao;

import java.math.BigDecimal;
import java.util.Date;

public class Movement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movement.idMovement
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    private Integer idMovement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movement.idMovementType
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    private Integer idMovementType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movement.amount
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movement.idMovementCut
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    private Integer idMovementCut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movement.idContributor
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    private Integer idContributor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movement.movementDate
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    private Date movementDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movement.description
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movement.createDate
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movement.updateDate
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movement.idMovement
     *
     * @return the value of movement.idMovement
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    public Integer getIdMovement() {
        return idMovement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movement.idMovement
     *
     * @param idMovement the value for movement.idMovement
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    public void setIdMovement(Integer idMovement) {
        this.idMovement = idMovement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movement.idMovementType
     *
     * @return the value of movement.idMovementType
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    public Integer getIdMovementType() {
        return idMovementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movement.idMovementType
     *
     * @param idMovementType the value for movement.idMovementType
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    public void setIdMovementType(Integer idMovementType) {
        this.idMovementType = idMovementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movement.amount
     *
     * @return the value of movement.amount
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movement.amount
     *
     * @param amount the value for movement.amount
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movement.idMovementCut
     *
     * @return the value of movement.idMovementCut
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    public Integer getIdMovementCut() {
        return idMovementCut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movement.idMovementCut
     *
     * @param idMovementCut the value for movement.idMovementCut
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    public void setIdMovementCut(Integer idMovementCut) {
        this.idMovementCut = idMovementCut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movement.idContributor
     *
     * @return the value of movement.idContributor
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    public Integer getIdContributor() {
        return idContributor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movement.idContributor
     *
     * @param idContributor the value for movement.idContributor
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    public void setIdContributor(Integer idContributor) {
        this.idContributor = idContributor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movement.movementDate
     *
     * @return the value of movement.movementDate
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    public Date getMovementDate() {
        return movementDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movement.movementDate
     *
     * @param movementDate the value for movement.movementDate
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    public void setMovementDate(Date movementDate) {
        this.movementDate = movementDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movement.description
     *
     * @return the value of movement.description
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movement.description
     *
     * @param description the value for movement.description
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movement.createDate
     *
     * @return the value of movement.createDate
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movement.createDate
     *
     * @param createDate the value for movement.createDate
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movement.updateDate
     *
     * @return the value of movement.updateDate
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movement.updateDate
     *
     * @param updateDate the value for movement.updateDate
     *
     * @mbggenerated Thu Sep 27 17:27:59 CDT 2012
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}