package org.iemm.sicomoro.db.dao;

import java.math.BigDecimal;
import java.util.Date;

public class MovementCut {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movementCut.idMovementCut
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    private Integer idMovementCut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movementCut.cutDate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    private Date cutDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movementCut.previousBalance
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    private BigDecimal previousBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movementCut.currentBalance
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    private BigDecimal currentBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movementCut.description
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movementCut.createDate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movementCut.updateDate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movementCut.idMovementCut
     *
     * @return the value of movementCut.idMovementCut
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public Integer getIdMovementCut() {
        return idMovementCut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movementCut.idMovementCut
     *
     * @param idMovementCut the value for movementCut.idMovementCut
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public void setIdMovementCut(Integer idMovementCut) {
        this.idMovementCut = idMovementCut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movementCut.cutDate
     *
     * @return the value of movementCut.cutDate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public Date getCutDate() {
        return cutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movementCut.cutDate
     *
     * @param cutDate the value for movementCut.cutDate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public void setCutDate(Date cutDate) {
        this.cutDate = cutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movementCut.previousBalance
     *
     * @return the value of movementCut.previousBalance
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public BigDecimal getPreviousBalance() {
        return previousBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movementCut.previousBalance
     *
     * @param previousBalance the value for movementCut.previousBalance
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public void setPreviousBalance(BigDecimal previousBalance) {
        this.previousBalance = previousBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movementCut.currentBalance
     *
     * @return the value of movementCut.currentBalance
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public BigDecimal getCurrentBalance() {
        return currentBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movementCut.currentBalance
     *
     * @param currentBalance the value for movementCut.currentBalance
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public void setCurrentBalance(BigDecimal currentBalance) {
        this.currentBalance = currentBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movementCut.description
     *
     * @return the value of movementCut.description
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movementCut.description
     *
     * @param description the value for movementCut.description
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movementCut.createDate
     *
     * @return the value of movementCut.createDate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movementCut.createDate
     *
     * @param createDate the value for movementCut.createDate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movementCut.updateDate
     *
     * @return the value of movementCut.updateDate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movementCut.updateDate
     *
     * @param updateDate the value for movementCut.updateDate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}