package org.iemm.sicomoro.db.dao;

import java.math.BigDecimal;
import java.util.Date;

public class Tax {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax.idTax
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    private Integer idTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax.name
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax.rate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    private BigDecimal rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax.createDate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax.updateDate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax.idTax
     *
     * @return the value of tax.idTax
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public Integer getIdTax() {
        return idTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax.idTax
     *
     * @param idTax the value for tax.idTax
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public void setIdTax(Integer idTax) {
        this.idTax = idTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax.name
     *
     * @return the value of tax.name
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax.name
     *
     * @param name the value for tax.name
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax.rate
     *
     * @return the value of tax.rate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax.rate
     *
     * @param rate the value for tax.rate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax.createDate
     *
     * @return the value of tax.createDate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax.createDate
     *
     * @param createDate the value for tax.createDate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax.updateDate
     *
     * @return the value of tax.updateDate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax.updateDate
     *
     * @param updateDate the value for tax.updateDate
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}