package org.iemm.sicomoro.db.client;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.iemm.sicomoro.db.dao.Contributor;
import org.iemm.sicomoro.db.dao.ContributorExample;

public interface ContributorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contributor
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    int countByExample(ContributorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contributor
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    int deleteByExample(ContributorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contributor
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    @Delete({
        "delete from contributor",
        "where idContributor = #{idContributor,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer idContributor);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contributor
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    @Insert({
        "insert into contributor (name, lastName, ",
        "secondLastName, createDate, ",
        "updateDate)",
        "values (#{name,jdbcType=VARCHAR}, #{lastName,jdbcType=VARCHAR}, ",
        "#{secondLastName,jdbcType=VARCHAR}, #{createDate,jdbcType=TIMESTAMP}, ",
        "#{updateDate,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="idContributor", before=false, resultType=Integer.class)
    int insert(Contributor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contributor
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    int insertSelective(Contributor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contributor
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    List<Contributor> selectByExample(ContributorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contributor
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    @Select({
        "select",
        "idContributor, name, lastName, secondLastName, createDate, updateDate",
        "from contributor",
        "where idContributor = #{idContributor,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Contributor selectByPrimaryKey(Integer idContributor);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contributor
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    int updateByExampleSelective(@Param("record") Contributor record, @Param("example") ContributorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contributor
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    int updateByExample(@Param("record") Contributor record, @Param("example") ContributorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contributor
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    int updateByPrimaryKeySelective(Contributor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contributor
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    @Update({
        "update contributor",
        "set name = #{name,jdbcType=VARCHAR},",
          "lastName = #{lastName,jdbcType=VARCHAR},",
          "secondLastName = #{secondLastName,jdbcType=VARCHAR},",
          "createDate = #{createDate,jdbcType=TIMESTAMP},",
          "updateDate = #{updateDate,jdbcType=TIMESTAMP}",
        "where idContributor = #{idContributor,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Contributor record);
}