package org.iemm.sicomoro.db.client;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.iemm.sicomoro.db.dao.Corte;
import org.iemm.sicomoro.db.dao.CorteExample;

public interface CorteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table corte
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    int countByExample(CorteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table corte
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    int deleteByExample(CorteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table corte
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    @Delete({
        "delete from corte",
        "where idCorte = #{idCorte,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer idCorte);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table corte
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    @Insert({
        "insert into corte (fechaCorte, saldoAnterior, ",
        "saldoActual, usuarioCreacion, ",
        "fechaCreacion, descripcion)",
        "values (#{fechaCorte,jdbcType=TIMESTAMP}, #{saldoAnterior,jdbcType=DECIMAL}, ",
        "#{saldoActual,jdbcType=DECIMAL}, #{usuarioCreacion,jdbcType=VARCHAR}, ",
        "#{fechaCreacion,jdbcType=TIMESTAMP}, #{descripcion,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="idCorte", before=false, resultType=Integer.class)
    int insert(Corte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table corte
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    int insertSelective(Corte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table corte
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    List<Corte> selectByExample(CorteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table corte
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    @Select({
        "select",
        "idCorte, fechaCorte, saldoAnterior, saldoActual, usuarioCreacion, fechaCreacion, ",
        "descripcion",
        "from corte",
        "where idCorte = #{idCorte,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Corte selectByPrimaryKey(Integer idCorte);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table corte
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    int updateByExampleSelective(@Param("record") Corte record, @Param("example") CorteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table corte
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    int updateByExample(@Param("record") Corte record, @Param("example") CorteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table corte
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    int updateByPrimaryKeySelective(Corte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table corte
     *
     * @mbggenerated Sat Aug 18 16:09:03 CDT 2012
     */
    @Update({
        "update corte",
        "set fechaCorte = #{fechaCorte,jdbcType=TIMESTAMP},",
          "saldoAnterior = #{saldoAnterior,jdbcType=DECIMAL},",
          "saldoActual = #{saldoActual,jdbcType=DECIMAL},",
          "usuarioCreacion = #{usuarioCreacion,jdbcType=VARCHAR},",
          "fechaCreacion = #{fechaCreacion,jdbcType=TIMESTAMP},",
          "descripcion = #{descripcion,jdbcType=VARCHAR}",
        "where idCorte = #{idCorte,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Corte record);
}