package org.iemm.sicomoro.db.client;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.iemm.sicomoro.db.dao.Movement;
import org.iemm.sicomoro.db.dao.MovementExample;

public interface MovementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movement
     *
     * @mbggenerated Sun Sep 02 15:34:07 CDT 2012
     */
    int countByExample(MovementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movement
     *
     * @mbggenerated Sun Sep 02 15:34:07 CDT 2012
     */
    int deleteByExample(MovementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movement
     *
     * @mbggenerated Sun Sep 02 15:34:07 CDT 2012
     */
    @Delete({
        "delete from movement",
        "where idMovement = #{idMovement,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer idMovement);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movement
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    @Insert({
        "insert into movement (idMovementType, amount, ",
        "idMovementCut, idContributor, ",
        "createDate, updateDate)",
        "values (#{idMovementType,jdbcType=INTEGER}, #{amount,jdbcType=DECIMAL}, ",
        "#{idMovementCut,jdbcType=INTEGER}, #{idContributor,jdbcType=INTEGER}, ",
        "#{createDate,jdbcType=TIMESTAMP}, #{updateDate,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="idMovement", before=false, resultType=Integer.class)
    int insert(Movement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movement
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    int insertSelective(Movement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movement
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    List<Movement> selectByExample(MovementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movement
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    @Select({
        "select",
        "idMovement, idMovementType, amount, idMovementCut, idContributor, createDate, ",
        "updateDate",
        "from movement",
        "where idMovement = #{idMovement,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Movement selectByPrimaryKey(Integer idMovement);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movement
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    int updateByExampleSelective(@Param("record") Movement record, @Param("example") MovementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movement
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    int updateByExample(@Param("record") Movement record, @Param("example") MovementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movement
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    int updateByPrimaryKeySelective(Movement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movement
     *
     * @mbggenerated Sun Sep 02 15:34:08 CDT 2012
     */
    @Update({
        "update movement",
        "set idMovementType = #{idMovementType,jdbcType=INTEGER},",
          "amount = #{amount,jdbcType=DECIMAL},",
          "idMovementCut = #{idMovementCut,jdbcType=INTEGER},",
          "idContributor = #{idContributor,jdbcType=INTEGER},",
          "createDate = #{createDate,jdbcType=TIMESTAMP},",
          "updateDate = #{updateDate,jdbcType=TIMESTAMP}",
        "where idMovement = #{idMovement,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Movement record);
}